### ISSUE TITLE
在中文路径下运行 python -matx gui会出现编码问题

### ISSUE THREAD

**Issue by yymihuak** [codeskyblue/AutomatorX#30]
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\atx\__main__.py", line 141, in <module>
    main()
  File "C:\Python27\lib\site-packages\atx\__main__.py", line 138, in main
    args.func(args)
  File "C:\Python27\lib\site-packages\atx\__main__.py", line 46, in _inner
    return inject(mod.main, pargs)
  File "C:\Python27\lib\site-packages\atx\__main__.py", line 37, in inject
    return func(*args)
  File "C:\Python27\lib\site-packages\atx\cmds\tkgui.py", line 363, in main
    d.wakeup()
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 797, in wak
eup
    self.server.jsonrpc.wakeUp()
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 430, in wra
pper
    server.start(timeout=30)
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 468, in sta
rt
    files = self.push()
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 404, in pus
h
    self.adb.cmd("push", filename, "/data/local/tmp/").wait()
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 288, in cmd

    return self.raw_cmd(*["-s", serial] + list(args))
  File "C:\Python27\lib\site-packages\uiautomator\__init__.py", line 297, in raw
_cmd
    return subprocess.Popen(cmd_line, shell=True, stdout=subprocess.PIPE, stderr
=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 913, in _execute_child
    args = list2cmdline(args)
  File "C:\Python27\lib\subprocess.py", line 644, in list2cmdline
    return ''.join(result)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 0: ordinal
not in range(128)

**Comment by codeskyblue** [comment]
复线不了，下次出现在说
