### ISSUE TITLE
python -m atx minicap 安装失败，必须指定端口到15073才能成功

### ISSUE THREAD

**Issue by 313077271** [codeskyblue/AutomatorX#53]
## What steps will reproduce the problem?
win 10 32位PC，atx安装完毕后，按照指示完成设备的连接（atx.connect()），未报错
命令行运行python -m atx minicap

## What do you see instead?
报错信息如下：
```
D:\duping\atx>python -m atx minicap
2016-07-29 10:58:29.029 INFO  [minicap:  55] Minicap install started!
2016-07-29 10:58:29.029 INFO  [minicap:  60] Make temp dir ...
2016-07-29 10:58:29.029 INFO  [minicap:  64] Retrive device information ...
2016-07-29 10:58:29.060 ERROR [minicap: 100] run cmd: adb -H 127.0.0.1 -P 5037 shell getprop ro.product.cpu.abi failed. Command 'adb -H 127.0.0.1 -P 5037 shell getprop ro.product.cpu.abi' returned non-zero exit status 1
2016-07-29 10:58:29.060 INFO  [minicap: 103] Cleaning temp dir
```

在命令中指定端口到15073后问题解决
Python -m atx -H 127.0.0.1 -P 15037 minicap

另，以下测试设备均有问题
小米5 6.0.1
三星note4 4.4.4
三星s3 4.3

**Comment by codeskyblue** [comment]
这个是电脑设置导致的问题，跟手机没有多大关系

**Comment by 313077271** [comment]
请问下，电脑还需要做哪些设置？按照文章的步骤进行了安装。另一台win 7 32位也是一样的问题。
环境变量中Path定义：
```
C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%JAVA_HOME%\bin;%ANDROID_HOME%\tools;%ANDROID_HOME%\platform-tools;C:\Python27;C:\Python27\Scripts;
```

**Comment by 313077271** [comment]
补充1：
1、在执行前杀掉所有adb进程，确认5037端口未被占用
```
D:\duping\atx>netstat -aon|findstr 5037

D:\duping\atx>
```
2、执行python -m atx minicap，查看5037端口的占用情况，如下：
```
D:\duping\atx>netstat -aon|findstr 5037

D:\duping\atx>
```
无相关进程，且任务管理器也无相关adb进程

补充2：
1、在执行前杀掉所有adb进程，确认5037端口未被占用
```
D:\duping\atx>netstat -aon|findstr 5037

D:\duping\atx>
```
2、执行python -m atx info，不断刷新查看5037端口的占用情况，如下：
```
D:\duping\atx>netstat -aon|findstr 5037

D:\duping\atx>netstat -aon|findstr 5037
  TCP    127.0.0.1:15037        0.0.0.0:0              LISTENING       7812

D:\duping\atx>netstat -aon|findstr 5037
  TCP    127.0.0.1:15037        0.0.0.0:0              LISTENING       7812
  TCP    127.0.0.1:15037        127.0.0.1:63433        TIME_WAIT       0
  TCP    127.0.0.1:63437        127.0.0.1:5037         SYN_SENT        3596

D:\duping\atx>netstat -aon|findstr 5037
  TCP    127.0.0.1:5037         0.0.0.0:0              LISTENING       2904
  TCP    127.0.0.1:15037        0.0.0.0:0              LISTENING       7812
  TCP    127.0.0.1:15037        127.0.0.1:63433        TIME_WAIT       0

D:\duping\atx>netstat -aon|findstr 5037
  TCP    127.0.0.1:5037         0.0.0.0:0              LISTENING       2904
  TCP    127.0.0.1:5037         127.0.0.1:63446        TIME_WAIT       0
  TCP    127.0.0.1:15037        0.0.0.0:0              LISTENING       7812
  TCP    127.0.0.1:15037        127.0.0.1:63433        TIME_WAIT       0

D:\duping\atx>netstat -aon|findstr 5037
  TCP    127.0.0.1:5037         0.0.0.0:0              LISTENING       2904
  TCP    127.0.0.1:15037        0.0.0.0:0              LISTENING       7812
```
指令本身报错
```
D:\duping\atx>python -matx info
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\atx\__main__.py", line 141, in <module>
    main()
  File "C:\Python27\lib\site-packages\atx\__main__.py", line 138, in main
    args.func(args)
  File "C:\Python27\lib\site-packages\atx\__main__.py", line 46, in _inner
    return inject(mod.main, pargs)
  File "C:\Python27\lib\site-packages\atx\__main__.py", line 37, in inject
    return func(*args)
  File "C:\Python27\lib\site-packages\atx\cmds\info.py", line 9, in main
    d = atx.connect(serial, host=host, port=port)
  File "C:\Python27\lib\site-packages\atx\__init__.py", line 54, in connect
    c = cls(*args, **kwargs)
  File "C:\Python27\lib\site-packages\atx\device\android.py", line 86, in __init__
    self._adb_device = self._adb_client.device(serialno)
  File "C:\Python27\lib\site-packages\atx\adbkit\client.py", line 119, in device
    raise EnvironmentError("Device not attached.")
EnvironmentError: Device not attached.
```

**Comment by 313077271** [comment]
确认是同事将电脑中adbserver端口固定为了15073，修改为5073后问题结局
