### ISSUE TITLE
Win7-32bit上安装失败

### ISSUE THREAD

**Issue by laiyuncong8404** [codeskyblue/AutomatorX#61]
安装Pillow模块时报错信息如下：
`Installing collected packages: atx, Pillow, atx-uiautomator, requests, subprocess32, tqdm, certifi
  Running setup.py install for Pillow
    Running command D:\Python27\python2.7.exe -c "import setuptools, tokenize;__file__='c:\\users\\admini~1\\appdata\\local\\temp\\pip_build_Administrator\\Pillow\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\admini~1\appdata\local\temp\pip-dmxmp2-record\install-record.txt --single-version-externally-managed --compile
    Single threaded build for windows
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    creating build\lib.win32-2.7\PIL
    copying PIL\BdfFontFile.py -> build\lib.win32-2.7\PIL
    copying PIL\BmpImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\BufrStubImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\ContainerIO.py -> build\lib.win32-2.7\PIL
    copying PIL\CurImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\DcxImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\DdsImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\EpsImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\ExifTags.py -> build\lib.win32-2.7\PIL
    copying PIL\features.py -> build\lib.win32-2.7\PIL
    copying PIL\FitsStubImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\FliImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\FontFile.py -> build\lib.win32-2.7\PIL
    copying PIL\FpxImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\FtexImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\GbrImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\GdImageFile.py -> build\lib.win32-2.7\PIL
    copying PIL\GifImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\GimpGradientFile.py -> build\lib.win32-2.7\PIL
    copying PIL\GimpPaletteFile.py -> build\lib.win32-2.7\PIL
    copying PIL\GribStubImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\Hdf5StubImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\IcnsImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\IcoImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\Image.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageChops.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageCms.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageColor.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageDraw.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageDraw2.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageEnhance.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageFile.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageFilter.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageFont.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageGrab.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageMath.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageMode.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageMorph.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageOps.py -> build\lib.win32-2.7\PIL
    copying PIL\ImagePalette.py -> build\lib.win32-2.7\PIL
    copying PIL\ImagePath.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageQt.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageSequence.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageShow.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageStat.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageTk.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageTransform.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageWin.py -> build\lib.win32-2.7\PIL
    copying PIL\ImImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\ImtImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\IptcImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\Jpeg2KImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\JpegImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\JpegPresets.py -> build\lib.win32-2.7\PIL
    copying PIL\McIdasImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\MicImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\MpegImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\MpoImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\MspImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\OleFileIO.py -> build\lib.win32-2.7\PIL
    copying PIL\PaletteFile.py -> build\lib.win32-2.7\PIL
    copying PIL\PalmImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PcdImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PcfFontFile.py -> build\lib.win32-2.7\PIL
    copying PIL\PcxImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PdfImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PixarImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PngImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PpmImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PsdImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PSDraw.py -> build\lib.win32-2.7\PIL
    copying PIL\PyAccess.py -> build\lib.win32-2.7\PIL
    copying PIL\SgiImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\SpiderImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\SunImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\TarIO.py -> build\lib.win32-2.7\PIL
    copying PIL\TgaImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\TiffImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\TiffTags.py -> build\lib.win32-2.7\PIL
    copying PIL\WalImageFile.py -> build\lib.win32-2.7\PIL
    copying PIL\WebPImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\WmfImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\XbmImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\XpmImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\XVThumbImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\_binary.py -> build\lib.win32-2.7\PIL
    copying PIL\_tkinter_finder.py -> build\lib.win32-2.7\PIL
    copying PIL\_util.py -> build\lib.win32-2.7\PIL
    copying PIL\__init__.py -> build\lib.win32-2.7\PIL
    running egg_info
    writing Pillow.egg-info\PKG-INFO
    writing top-level names to Pillow.egg-info\top_level.txt
    writing dependency_links to Pillow.egg-info\dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs\_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info\SOURCES.txt'
    copying PIL\OleFileIO-README.md -> build\lib.win32-2.7\PIL
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admini~1\appdata\local\temp\pip_build_Administrator\Pillow\setup.py", line 753, in <module>
        zip_safe=not debug_build(), )
      File "D:\Python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "D:\Python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "D:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "D:\Python27\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "D:\Python27\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "D:\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "D:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "D:\Python27\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "D:\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "D:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "D:\Python27\lib\distutils\command\build_ext.py", line 337, in run
        self.build_extensions()
      File "c:\users\admini~1\appdata\local\temp\pip_build_Administrator\Pillow\setup.py", line 521, in build_extensions
        ' using --disable-%s, aborting' % (f, f))
    ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting
    Complete output from command D:\Python27\python2.7.exe -c "import setuptools, tokenize;__file__='c:\\users\\admini~1\\appdata\\local\\temp\\pip_build_Administrator\\Pillow\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\admini~1\appdata\local\temp\pip-dmxmp2-record\install-record.txt --single-version-externally-managed --compile:
    Single threaded build for windows

running install

running build

running build_py

creating build

creating build\lib.win32-2.7

creating build\lib.win32-2.7\PIL

copying PIL\BdfFontFile.py -> build\lib.win32-2.7\PIL

copying PIL\BmpImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\BufrStubImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\ContainerIO.py -> build\lib.win32-2.7\PIL

copying PIL\CurImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\DcxImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\DdsImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\EpsImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\ExifTags.py -> build\lib.win32-2.7\PIL

copying PIL\features.py -> build\lib.win32-2.7\PIL

copying PIL\FitsStubImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\FliImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\FontFile.py -> build\lib.win32-2.7\PIL

copying PIL\FpxImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\FtexImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\GbrImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\GdImageFile.py -> build\lib.win32-2.7\PIL

copying PIL\GifImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\GimpGradientFile.py -> build\lib.win32-2.7\PIL

copying PIL\GimpPaletteFile.py -> build\lib.win32-2.7\PIL

copying PIL\GribStubImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\Hdf5StubImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\IcnsImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\IcoImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\Image.py -> build\lib.win32-2.7\PIL

copying PIL\ImageChops.py -> build\lib.win32-2.7\PIL

copying PIL\ImageCms.py -> build\lib.win32-2.7\PIL

copying PIL\ImageColor.py -> build\lib.win32-2.7\PIL

copying PIL\ImageDraw.py -> build\lib.win32-2.7\PIL

copying PIL\ImageDraw2.py -> build\lib.win32-2.7\PIL

copying PIL\ImageEnhance.py -> build\lib.win32-2.7\PIL

copying PIL\ImageFile.py -> build\lib.win32-2.7\PIL

copying PIL\ImageFilter.py -> build\lib.win32-2.7\PIL

copying PIL\ImageFont.py -> build\lib.win32-2.7\PIL

copying PIL\ImageGrab.py -> build\lib.win32-2.7\PIL

copying PIL\ImageMath.py -> build\lib.win32-2.7\PIL

copying PIL\ImageMode.py -> build\lib.win32-2.7\PIL

copying PIL\ImageMorph.py -> build\lib.win32-2.7\PIL

copying PIL\ImageOps.py -> build\lib.win32-2.7\PIL

copying PIL\ImagePalette.py -> build\lib.win32-2.7\PIL

copying PIL\ImagePath.py -> build\lib.win32-2.7\PIL

copying PIL\ImageQt.py -> build\lib.win32-2.7\PIL

copying PIL\ImageSequence.py -> build\lib.win32-2.7\PIL

copying PIL\ImageShow.py -> build\lib.win32-2.7\PIL

copying PIL\ImageStat.py -> build\lib.win32-2.7\PIL

copying PIL\ImageTk.py -> build\lib.win32-2.7\PIL

copying PIL\ImageTransform.py -> build\lib.win32-2.7\PIL

copying PIL\ImageWin.py -> build\lib.win32-2.7\PIL

copying PIL\ImImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\ImtImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\IptcImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\Jpeg2KImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\JpegImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\JpegPresets.py -> build\lib.win32-2.7\PIL

copying PIL\McIdasImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\MicImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\MpegImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\MpoImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\MspImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\OleFileIO.py -> build\lib.win32-2.7\PIL

copying PIL\PaletteFile.py -> build\lib.win32-2.7\PIL

copying PIL\PalmImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PcdImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PcfFontFile.py -> build\lib.win32-2.7\PIL

copying PIL\PcxImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PdfImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PixarImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PngImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PpmImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PsdImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PSDraw.py -> build\lib.win32-2.7\PIL

copying PIL\PyAccess.py -> build\lib.win32-2.7\PIL

copying PIL\SgiImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\SpiderImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\SunImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\TarIO.py -> build\lib.win32-2.7\PIL

copying PIL\TgaImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\TiffImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\TiffTags.py -> build\lib.win32-2.7\PIL

copying PIL\WalImageFile.py -> build\lib.win32-2.7\PIL

copying PIL\WebPImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\WmfImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\XbmImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\XpmImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\XVThumbImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\_binary.py -> build\lib.win32-2.7\PIL

copying PIL\_tkinter_finder.py -> build\lib.win32-2.7\PIL

copying PIL\_util.py -> build\lib.win32-2.7\PIL

copying PIL\__init__.py -> build\lib.win32-2.7\PIL

running egg_info

writing Pillow.egg-info\PKG-INFO

writing top-level names to Pillow.egg-info\top_level.txt

writing dependency_links to Pillow.egg-info\dependency_links.txt

warning: manifest_maker: standard file '-c' not found

reading manifest file 'Pillow.egg-info\SOURCES.txt'

reading manifest template 'MANIFEST.in'

warning: no files found matching '*.sh'

no previously-included directories found matching 'docs\_static'

warning: no previously-included files found matching '.coveragerc'

warning: no previously-included files found matching '.editorconfig'

warning: no previously-included files found matching '.landscape.yaml'

warning: no previously-included files found matching 'appveyor.yml'

warning: no previously-included files found matching 'build_children.sh'

warning: no previously-included files found matching 'tox.ini'

warning: no previously-included files matching '.git*' found anywhere in distribution

warning: no previously-included files matching '*.pyc' found anywhere in distribution

warning: no previously-included files matching '*.so' found anywhere in distribution

writing manifest file 'Pillow.egg-info\SOURCES.txt'

copying PIL\OleFileIO-README.md -> build\lib.win32-2.7\PIL

running build_ext

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "c:\users\admini~1\appdata\local\temp\pip_build_Administrator\Pillow\setup.py", line 753, in <module>

    zip_safe=not debug_build(), )

  File "D:\Python27\lib\distutils\core.py", line 151, in setup

    dist.run_commands()

  File "D:\Python27\lib\distutils\dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "D:\Python27\lib\distutils\dist.py", line 972, in run_command

    cmd_obj.run()

  File "D:\Python27\lib\site-packages\setuptools\command\install.py", line 61, in run

    return orig.install.run(self)

  File "D:\Python27\lib\distutils\command\install.py", line 563, in run

    self.run_command('build')

  File "D:\Python27\lib\distutils\cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "D:\Python27\lib\distutils\dist.py", line 972, in run_command

    cmd_obj.run()

  File "D:\Python27\lib\distutils\command\build.py", line 127, in run

    self.run_command(cmd_name)

  File "D:\Python27\lib\distutils\cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "D:\Python27\lib\distutils\dist.py", line 972, in run_command

    cmd_obj.run()

  File "D:\Python27\lib\distutils\command\build_ext.py", line 337, in run

    self.build_extensions()

  File "c:\users\admini~1\appdata\local\temp\pip_build_Administrator\Pillow\setup.py", line 521, in build_extensions

    ' using --disable-%s, aborting' % (f, f))

ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting

----------------------------------------
Cleaning up...
  Removing temporary dir c:\users\admini~1\appdata\local\temp\pip_build_Administrator...
Command D:\Python27\python2.7.exe -c "import setuptools, tokenize;__file__='c:\\users\\admini~1\\appdata\\local\\temp\\pip_build_Administrator\\Pillow\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\admini~1\appdata\local\temp\pip-dmxmp2-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\admini~1\appdata\local\temp\pip_build_Administrator\Pillow
Exception information:
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "D:\Python27\lib\site-packages\pip\commands\install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "D:\Python27\lib\site-packages\pip\req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "D:\Python27\lib\site-packages\pip\req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "D:\Python27\lib\site-packages\pip\util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command D:\Python27\python2.7.exe -c "import setuptools, tokenize;__file__='c:\\users\\admini~1\\appdata\\local\\temp\\pip_build_Administrator\\Pillow\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\admini~1\appdata\local\temp\pip-dmxmp2-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in c:\users\admini~1\appdata\local\temp\pip_build_Administrator\Pillow`

**Comment by laiyuncong8404** [comment]
我后来下载了exe安装，解决了这个问题。
但是后续碰到tqdm和subprocess32模块需要手动安装的问题，先已解决。
